import type { Product, Order, Category, Audience } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: "p1", name: "Body manga larga rayado", category: "bodies", audience: "bebe",
    price: 8900, compareAt: 11500,
    stock: { "0-3M": 5, "3-6M": 8, "6-12M": 4, "12-18M": 2 },
    colors: ["crema", "salvia"],
    description: "Body de algodón pima con broches a presión en la entrepierna. Suave, transpirable y perfecto para el día a día.",
    materials: "100% algodón pima", care: "Lavar a máquina con agua fría. No usar lavandina.",
    tags: ["nuevo", "best-seller"],
    img: "https://images.unsplash.com/photo-1522771930-78848d9293e8?w=800&q=80",
  },
  {
    id: "p2", name: "Conjunto buzo + jogger salvia", category: "conjuntos", audience: "nino",
    price: 18500, compareAt: null,
    stock: { "2": 3, "4": 6, "6": 4 },
    colors: ["salvia", "terracota"],
    description: "Conjunto de friza liviana, ideal para entretiempo. Buzo con bolsillo canguro y jogger con cintura elastizada.",
    materials: "Algodón 80% / Poliéster 20%", care: "Lavar del revés. No planchar estampa.",
    tags: ["best-seller"],
    img: "https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=800&q=80",
  },
  {
    id: "p3", name: "Pijama dos piezas estrellas", category: "pijamas", audience: "nino",
    price: 14200, compareAt: 16900,
    stock: { "2": 2, "4": 5, "6": 3 },
    colors: ["crema", "rosa-viejo"],
    description: "Pijama de modal con estampa de estrellitas. Remera manga larga y pantalón con puño.",
    materials: "Modal 95% / Spandex 5%", care: "Lavar a máquina. Secar al aire.",
    tags: ["oferta"],
    img: "https://images.unsplash.com/photo-1519278409-1f56fdda7fe5?w=800&q=80",
  },
  {
    id: "p4", name: "Vestido boho flores", category: "vestidos", audience: "nino",
    price: 16900, compareAt: null,
    stock: { "2": 4, "4": 4, "6": 2 },
    colors: ["beige", "terracota"],
    description: "Vestido de viscosa fluida con estampa floral. Tira regulable en hombros.",
    materials: "Viscosa 100%", care: "Lavar a mano preferentemente.",
    tags: ["nuevo"],
    img: "https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=800&q=80",
  },
  {
    id: "p5", name: "Conjunto recién nacido tres piezas", category: "conjuntos", audience: "recien-nacido",
    price: 22500, compareAt: 26000,
    stock: { "RN": 8, "0-3M": 6 },
    colors: ["crema"],
    description: "Set de bienvenida: body, pantalón y gorrito. Tela super suave hipoalergénica.",
    materials: "Algodón pima 100%", care: "Lavar con jabón neutro.",
    tags: ["nuevo", "regalo"],
    img: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800&q=80",
  },
  {
    id: "p6", name: "Campera de friza con capucha", category: "abrigos", audience: "nino",
    price: 24900, compareAt: null,
    stock: { "2": 0, "4": 3, "6": 2 },
    colors: ["terracota", "salvia"],
    description: "Campera con capucha forrada y cierre frontal. Bolsillos canguro.",
    materials: "Friza pesada de algodón", care: "Lavar a máquina ciclo suave.",
    tags: [],
    img: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&q=80",
  },
  {
    id: "p7", name: "Body bordado animalitos", category: "bodies", audience: "bebe",
    price: 9900, compareAt: null,
    stock: { "3-6M": 4, "6-12M": 6, "12-18M": 3 },
    colors: ["crema", "celeste-suave"],
    description: "Body con bordados de animalitos en el frente. Cuello americano para fácil cambio.",
    materials: "Algodón pima 100%", care: "Lavar del revés.",
    tags: ["best-seller"],
    img: "https://images.unsplash.com/photo-1503944168849-8bf86875b08e?w=800&q=80",
  },
  {
    id: "p8", name: "Gorrito tejido orejitas", category: "accesorios", audience: "recien-nacido",
    price: 5500, compareAt: null,
    stock: { "RN": 12, "0-6M": 8 },
    colors: ["crema", "beige", "salvia"],
    description: "Gorrito tejido a mano con orejitas. Forrado en algodón.",
    materials: "Lana merino / Forro algodón", care: "Lavar a mano agua fría.",
    tags: ["regalo"],
    img: "https://images.unsplash.com/photo-1544487102-26142b0e4f63?w=800&q=80",
  },
  {
    id: "p9", name: "Mameluco invierno", category: "abrigos", audience: "bebe",
    price: 28900, compareAt: 32000,
    stock: { "0-6M": 3, "6-12M": 4, "12-18M": 2 },
    colors: ["beige", "terracota"],
    description: "Mameluco enterizo de friza con cierre completo. Puños y tobillos elastizados.",
    materials: "Friza polar", care: "Lavar a máquina.",
    tags: ["oferta"],
    img: "https://images.unsplash.com/photo-1607453998774-d533f65dac99?w=800&q=80",
  },
  {
    id: "p10", name: "Set babitas de algodón x3", category: "accesorios", audience: "recien-nacido",
    price: 7900, compareAt: null,
    stock: { "Único": 25 },
    colors: ["crema-mix"],
    description: "Pack de 3 babitas con broche a presión. Lado absorbente y lado impermeable.",
    materials: "Algodón / PUL", care: "Lavar a máquina.",
    tags: [],
    img: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80",
  },
  {
    id: "p11", name: "Remera oversize estampada", category: "remeras", audience: "nino",
    price: 11500, compareAt: null,
    stock: { "2": 5, "4": 7, "6": 5 },
    colors: ["crema", "salvia"],
    description: "Remera de algodón con caída oversize. Estampa minimalista al frente.",
    materials: "Algodón jersey 100%", care: "Lavar del revés.",
    tags: ["nuevo"],
    img: "https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=800&q=80",
  },
  {
    id: "p12", name: "Jogger frizado básico", category: "pantalones", audience: "nino",
    price: 13500, compareAt: null,
    stock: { "2": 6, "4": 8, "6": 4 },
    colors: ["beige", "terracota", "salvia"],
    description: "Jogger de friza con cintura elastizada y cordón. Bolsillos laterales.",
    materials: "Friza algodón", care: "Lavar del revés.",
    tags: ["best-seller"],
    img: "https://images.unsplash.com/photo-1519278409-1f56fdda7fe5?w=800&q=80",
  },
];

export const CATEGORIES: Category[] = [
  { id: "bodies", label: "Bodies", icon: "✿" },
  { id: "conjuntos", label: "Conjuntos", icon: "❋" },
  { id: "pijamas", label: "Pijamas", icon: "☾" },
  { id: "vestidos", label: "Vestidos", icon: "✦" },
  { id: "abrigos", label: "Abrigos", icon: "❅" },
  { id: "remeras", label: "Remeras", icon: "♡" },
  { id: "pantalones", label: "Pantalones", icon: "❖" },
  { id: "accesorios", label: "Accesorios", icon: "✧" },
];

export const AUDIENCES: Audience[] = [
  { id: "recien-nacido", label: "Recién nacido", range: "0–3 meses" },
  { id: "bebe", label: "Bebé", range: "3–24 meses" },
  { id: "nino", label: "Niño/a", range: "2–6 años" },
];

export const INITIAL_ORDERS: Order[] = [
  { id: "ULB-2841", customer: "María Fernández", email: "maria.f@gmail.com", date: "2026-05-04", status: "preparando", items: 3, total: 42700, payment: "Tarjeta", shipping: "Andreani a Domicilio", address: "Av. Cabildo 2840, CABA" },
  { id: "ULB-2840", customer: "Lucía Romero", email: "lu.romero@hotmail.com", date: "2026-05-04", status: "enviado", items: 2, total: 27400, payment: "Transferencia", shipping: "Cadetería local", address: "Soler 4521, CABA" },
  { id: "ULB-2839", customer: "Sofía Paz", email: "sofi.paz@gmail.com", date: "2026-05-03", status: "entregado", items: 5, total: 86200, payment: "Tarjeta", shipping: "Andreani Sucursal", address: "Suc. Belgrano" },
  { id: "ULB-2838", customer: "Camila Ortiz", email: "cami.ortiz@gmail.com", date: "2026-05-03", status: "preparando", items: 1, total: 14200, payment: "Transferencia", shipping: "Cadetería local", address: "Honduras 5230, CABA" },
  { id: "ULB-2837", customer: "Florencia Díaz", email: "flor.d@gmail.com", date: "2026-05-02", status: "pendiente-pago", items: 2, total: 22400, payment: "Transferencia", shipping: "Andreani a Domicilio", address: "Av. Pueyrredón 1212, CABA" },
  { id: "ULB-2836", customer: "Valentina Cruz", email: "vale.cruz@gmail.com", date: "2026-05-01", status: "entregado", items: 4, total: 65900, payment: "Tarjeta", shipping: "Andreani a Domicilio", address: "Av. Rivadavia 8901, CABA" },
];

export const fmt = (n: number): string =>
  "$" + Number(n).toLocaleString("es-AR", { maximumFractionDigits: 0 });
